Dz3
neu3n0/2022-2-VK-EDU-FS-Frontend-M-Knyazev pull request #5
Opened 2022-11-08 10:23 UTC by neu3n0

# Домашнее задание №3

Прошу @martinkomitsky, @haseprogram или @vaganov-spb проверить его.

Что было сделано:
* Шапка (с кнопкой поиска, заголовком, кнопкой "бургер")
* Чат (с аватаром, заголовком, последним сообщением, временем и индикатором прочитанности/доставленности)
* "Парящая" кнопка "создать чат"
* Предусмотрен переход с экрана списка чатов на экран сообщений

2022-11-09 20:32 UTC, martinkomitsky requested changes
Не исправлен конфликт.
Это базовая проверка перед тем, как сдать дз.
А еще в инструкции сказано, что надо делать, чтобы не допускать конфликты

2022-11-09 22:54 UTC, neu3n0 commented
@martinkomitsky Здравствуйте, что-то я совсем не заметил и не ожидал этого, исправил.

2022-11-09 23:09 UTC, neu3n0 commented
@martinkomitsky А еще хотелось бы узнать. Нам обязательно по стилю надо делать как в макете? Или можно делать немного другой дизайн.

2022-11-09 23:17 UTC, martinkomitsky commented
> @martinkomitsky А еще хотелось бы узнать. Нам обязательно по стилю надо делать как в макете? Или можно делать немного другой дизайн.

Можно немного другой, но чтобы функционально он оставался прежним

2022-11-11 18:41 UTC, martinkomitsky approved these changes
Отлично! Жаль, что с опозданием( 
7

2022-11-11 18:41 UTC, merged